name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Matches your setup

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests with Flaky Detection
        run: |
          echo "Running tests 5 times to detect flakiness..."
          failures=0
          for i in {1..5}; do
            echo "Test run $i"
            npm test && echo "Pass" || { echo "Fail"; failures=$((failures+1)); }
          done
          echo "Total failures: $failures"
          if [ $failures -gt 1 ]; then
            echo "Too many flaky test failures!"
            exit 1  # Fails the pipeline if flakiness exceeds threshold
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t altheris:latest .  # Lowercase for consistency (Docker convention)

      - name: Run Containerized Tests
        run: docker run altheris:latest npm test || echo "Containerized tests failed, proceeding anyway"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag altheris:latest ${{ secrets.DOCKER_USERNAME }}/altheris:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/altheris:latest





          docker login -u lakshayp


          dckr_pat_Ny3iPKKOO5eNSSln4Ikri8o-c14