name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./app
        run: npm install

      - name: Run Jest Tests with Flaky Detection
        working-directory: ./app
        run: |
          echo "Running tests 5 times to detect flakiness..."
          failures=0
          for i in {1..5}; do
            echo "Test run $i"
            npm test && echo "Pass" || { echo "Fail"; failures=$((failures+1)); }
          done
          echo "Total failures: $failures"
          if [ $failures -gt 1 ]; then
            echo "Too many flaky test failures!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: ./app
        run: docker build -t app:latest .

      - name: Run Containerized Tests
        run: docker run app:latest npm test || echo "Containerized tests failed, proceeding anyway"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker Images
        run: |
          docker tag app:latest ${{ secrets.DOCKER_USERNAME }}/app:latest
          docker tag app:latest ${{ secrets.DOCKER_USERNAME }}/app:stable
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/app:stable